/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.warrantchange.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WarrantUserUniqueId service. Represents a row in the &quot;warrantUserUniqueId&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.warrantchange.model.impl.WarrantUserUniqueIdModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.warrantchange.model.impl.WarrantUserUniqueIdImpl}.
 * </p>
 *
 * @author davidk
 * @see WarrantUserUniqueId
 * @see com.warrantchange.model.impl.WarrantUserUniqueIdImpl
 * @see com.warrantchange.model.impl.WarrantUserUniqueIdModelImpl
 * @generated
 */
public interface WarrantUserUniqueIdModel extends BaseModel<WarrantUserUniqueId> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a WarrantUserUniqueId model instance should use the {@link WarrantUserUniqueId} interface instead.
	 */

	/**
	 * Returns the primary key of this WarrantUserUniqueId.
	 *
	 * @return the primary key of this WarrantUserUniqueId
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this WarrantUserUniqueId.
	 *
	 * @param primaryKey the primary key of this WarrantUserUniqueId
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this WarrantUserUniqueId.
	 *
	 * @return the ID of this WarrantUserUniqueId
	 */
	public long getId();

	/**
	 * Sets the ID of this WarrantUserUniqueId.
	 *
	 * @param id the ID of this WarrantUserUniqueId
	 */
	public void setId(long id);

	/**
	 * Returns the unique ID of this WarrantUserUniqueId.
	 *
	 * @return the unique ID of this WarrantUserUniqueId
	 */
	@AutoEscape
	public String getUniqueId();

	/**
	 * Sets the unique ID of this WarrantUserUniqueId.
	 *
	 * @param uniqueId the unique ID of this WarrantUserUniqueId
	 */
	public void setUniqueId(String uniqueId);

	/**
	 * Returns the user ID of this WarrantUserUniqueId.
	 *
	 * @return the user ID of this WarrantUserUniqueId
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this WarrantUserUniqueId.
	 *
	 * @param userId the user ID of this WarrantUserUniqueId
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this WarrantUserUniqueId.
	 *
	 * @return the user uuid of this WarrantUserUniqueId
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this WarrantUserUniqueId.
	 *
	 * @param userUuid the user uuid of this WarrantUserUniqueId
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this WarrantUserUniqueId.
	 *
	 * @return the create date of this WarrantUserUniqueId
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this WarrantUserUniqueId.
	 *
	 * @param createDate the create date of this WarrantUserUniqueId
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this WarrantUserUniqueId.
	 *
	 * @return the modified date of this WarrantUserUniqueId
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this WarrantUserUniqueId.
	 *
	 * @param modifiedDate the modified date of this WarrantUserUniqueId
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sent email of this WarrantUserUniqueId.
	 *
	 * @return the sent email of this WarrantUserUniqueId
	 */
	@AutoEscape
	public String getSentEmail();

	/**
	 * Sets the sent email of this WarrantUserUniqueId.
	 *
	 * @param sentEmail the sent email of this WarrantUserUniqueId
	 */
	public void setSentEmail(String sentEmail);

	/**
	 * Returns the sent date of this WarrantUserUniqueId.
	 *
	 * @return the sent date of this WarrantUserUniqueId
	 */
	public Date getSentDate();

	/**
	 * Sets the sent date of this WarrantUserUniqueId.
	 *
	 * @param sentDate the sent date of this WarrantUserUniqueId
	 */
	public void setSentDate(Date sentDate);

	/**
	 * Returns the sent omicode of this WarrantUserUniqueId.
	 *
	 * @return the sent omicode of this WarrantUserUniqueId
	 */
	@AutoEscape
	public String getSentOmicode();

	/**
	 * Sets the sent omicode of this WarrantUserUniqueId.
	 *
	 * @param sentOmicode the sent omicode of this WarrantUserUniqueId
	 */
	public void setSentOmicode(String sentOmicode);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WarrantUserUniqueId warrantUserUniqueId);

	public int hashCode();

	public CacheModel<WarrantUserUniqueId> toCacheModel();

	public WarrantUserUniqueId toEscapedModel();

	public String toString();

	public String toXmlString();
}