/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.warrantchange.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.base.PrincipalBean;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.warrantchange.model.Warrant;

import com.warrantchange.service.WarrantLocalService;
import com.warrantchange.service.WarrantService;
import com.warrantchange.service.WarrantUserUniqueIdLocalService;
import com.warrantchange.service.WarrantUserUniqueIdService;
import com.warrantchange.service.persistence.WarrantPersistence;
import com.warrantchange.service.persistence.WarrantUserUniqueIdPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the Warrant remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.warrantchange.service.impl.WarrantServiceImpl}.
 * </p>
 *
 * @author davidk
 * @see com.warrantchange.service.impl.WarrantServiceImpl
 * @see com.warrantchange.service.WarrantServiceUtil
 * @generated
 */
public abstract class WarrantServiceBaseImpl extends PrincipalBean
	implements WarrantService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.warrantchange.service.WarrantServiceUtil} to access the Warrant remote service.
	 */

	/**
	 * Returns the Warrant local service.
	 *
	 * @return the Warrant local service
	 */
	public WarrantLocalService getWarrantLocalService() {
		return warrantLocalService;
	}

	/**
	 * Sets the Warrant local service.
	 *
	 * @param warrantLocalService the Warrant local service
	 */
	public void setWarrantLocalService(WarrantLocalService warrantLocalService) {
		this.warrantLocalService = warrantLocalService;
	}

	/**
	 * Returns the Warrant remote service.
	 *
	 * @return the Warrant remote service
	 */
	public WarrantService getWarrantService() {
		return warrantService;
	}

	/**
	 * Sets the Warrant remote service.
	 *
	 * @param warrantService the Warrant remote service
	 */
	public void setWarrantService(WarrantService warrantService) {
		this.warrantService = warrantService;
	}

	/**
	 * Returns the Warrant persistence.
	 *
	 * @return the Warrant persistence
	 */
	public WarrantPersistence getWarrantPersistence() {
		return warrantPersistence;
	}

	/**
	 * Sets the Warrant persistence.
	 *
	 * @param warrantPersistence the Warrant persistence
	 */
	public void setWarrantPersistence(WarrantPersistence warrantPersistence) {
		this.warrantPersistence = warrantPersistence;
	}

	/**
	 * Returns the WarrantUserUniqueId local service.
	 *
	 * @return the WarrantUserUniqueId local service
	 */
	public WarrantUserUniqueIdLocalService getWarrantUserUniqueIdLocalService() {
		return warrantUserUniqueIdLocalService;
	}

	/**
	 * Sets the WarrantUserUniqueId local service.
	 *
	 * @param warrantUserUniqueIdLocalService the WarrantUserUniqueId local service
	 */
	public void setWarrantUserUniqueIdLocalService(
		WarrantUserUniqueIdLocalService warrantUserUniqueIdLocalService) {
		this.warrantUserUniqueIdLocalService = warrantUserUniqueIdLocalService;
	}

	/**
	 * Returns the WarrantUserUniqueId remote service.
	 *
	 * @return the WarrantUserUniqueId remote service
	 */
	public WarrantUserUniqueIdService getWarrantUserUniqueIdService() {
		return warrantUserUniqueIdService;
	}

	/**
	 * Sets the WarrantUserUniqueId remote service.
	 *
	 * @param warrantUserUniqueIdService the WarrantUserUniqueId remote service
	 */
	public void setWarrantUserUniqueIdService(
		WarrantUserUniqueIdService warrantUserUniqueIdService) {
		this.warrantUserUniqueIdService = warrantUserUniqueIdService;
	}

	/**
	 * Returns the WarrantUserUniqueId persistence.
	 *
	 * @return the WarrantUserUniqueId persistence
	 */
	public WarrantUserUniqueIdPersistence getWarrantUserUniqueIdPersistence() {
		return warrantUserUniqueIdPersistence;
	}

	/**
	 * Sets the WarrantUserUniqueId persistence.
	 *
	 * @param warrantUserUniqueIdPersistence the WarrantUserUniqueId persistence
	 */
	public void setWarrantUserUniqueIdPersistence(
		WarrantUserUniqueIdPersistence warrantUserUniqueIdPersistence) {
		this.warrantUserUniqueIdPersistence = warrantUserUniqueIdPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return Warrant.class;
	}

	protected String getModelClassName() {
		return Warrant.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = warrantPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = WarrantLocalService.class)
	protected WarrantLocalService warrantLocalService;
	@BeanReference(type = WarrantService.class)
	protected WarrantService warrantService;
	@BeanReference(type = WarrantPersistence.class)
	protected WarrantPersistence warrantPersistence;
	@BeanReference(type = WarrantUserUniqueIdLocalService.class)
	protected WarrantUserUniqueIdLocalService warrantUserUniqueIdLocalService;
	@BeanReference(type = WarrantUserUniqueIdService.class)
	protected WarrantUserUniqueIdService warrantUserUniqueIdService;
	@BeanReference(type = WarrantUserUniqueIdPersistence.class)
	protected WarrantUserUniqueIdPersistence warrantUserUniqueIdPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
}